import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatCurrency, formatQuantity, ProductRecord, toNumber } from "@/lib/commerce";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, Loader2, PackageCheck } from "lucide-react";
import { useLocation } from "wouter";

export default function LowStock() {
  const [_, setLocation] = useLocation();
  const { data: products = [], isLoading } = trpc.commerce.products.lowStock.useQuery();
  return <div className="space-y-6"><section><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#8a660f]">Reposição</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-[#193c32]">Estoque baixo</h1><p className="mt-2 text-sm text-[#6b786f]">Itens que atingiram ou ficaram abaixo do nível mínimo configurado.</p></section><section className="overflow-hidden rounded-2xl border border-[#ead9ad] bg-white shadow-[0_4px_18px_rgba(71,54,18,0.04)]"><div className="flex items-center gap-3 border-b border-[#f1e8d0] bg-[#fffaf0] px-5 py-4"><div className="grid size-10 place-items-center rounded-xl bg-[#fff0c9] text-[#9a5d08]"><AlertTriangle className="size-5"/></div><div><p className="font-semibold text-[#584313]">{products.length} produto(s) precisam de reposição</p><p className="text-xs text-[#8d7950]">O alerta desaparece automaticamente quando o estoque é ajustado acima do mínimo.</p></div></div>{isLoading ? <div className="grid h-60 place-items-center"><Loader2 className="size-5 animate-spin text-[#9a5d08]"/></div> : products.length ? <div className="divide-y divide-[#f0ede4]">{(products as ProductRecord[]).map(product => { const missing = Math.max(0, toNumber(product.stockMinimum) - toNumber(product.stockCurrent)); return <div key={product.id} className="flex flex-col gap-4 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="font-semibold text-[#283e31]">{product.name}</p><p className="mt-1 text-xs text-[#748178]">Venda: {formatCurrency(product.salePrice)} por {product.unit === "kg" ? "kg" : "unidade"}</p></div><div className="grid grid-cols-3 gap-4 text-left sm:text-right"><div><p className="text-[10px] font-bold uppercase tracking-wide text-[#8b877a]">Atual</p><p className="mt-1 font-semibold text-[#a05d08]">{formatQuantity(product.stockCurrent, product.unit)}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-[#8b877a]">Mínimo</p><p className="mt-1 font-semibold text-[#46564c]">{formatQuantity(product.stockMinimum, product.unit)}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-[#8b877a]">Faltam</p><p className="mt-1 font-semibold text-[#a05d08]">{formatQuantity(missing, product.unit)}</p></div></div><Button onClick={() => setLocation("/produtos")} variant="outline" className="h-9 rounded-xl border-[#ddcfaa] text-[#6b5015] hover:bg-[#fff8e9]">Ajustar <ArrowRight className="ml-1 size-4"/></Button></div>; })}</div> : <div className="grid min-h-80 place-items-center px-6 text-center"><div><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#e5f2d6] text-[#286144]"><PackageCheck className="size-6"/></div><p className="mt-4 font-semibold text-[#294536]">Tudo certo com o estoque</p><p className="mt-1 text-sm text-[#748178]">Não há produtos no nível mínimo ou abaixo dele.</p><Badge className="mt-4 border-0 bg-[#e5f2d6] text-[#286144]">Níveis saudáveis</Badge></div></div>}</section></div>;
}
